# Generated by Django 4.1.3 on 2023-02-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dtu_tokens',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='thapar_tokens',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
